export const STAGING_CLIENT=String.raw`(()=>{
'use strict';
if(window.__DINI_V3_PRODUCTION_UI_STAGING__)return;
window.__DINI_V3_PRODUCTION_UI_STAGING__=true;
const VERSION='3.10.0-staging.1',nativeFetch=window.fetch.bind(window),unsafe=new Set(['POST','PUT','PATCH','DELETE']);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function urlOf(input){try{return new URL(typeof input==='string'?input:input?.url||'',location.href)}catch{return null}}
function methodOf(input,init){return String(init?.method||input?.method||'GET').toUpperCase()}
window.fetch=(input,init={})=>{const u=urlOf(input),m=methodOf(input,init);if(u&&/\.supabase\.co$/i.test(u.hostname)&&unsafe.has(m)&&/^\/(?:rest|storage|functions)\/v1\//.test(u.pathname)){notify('warning','STAGING READ-ONLY','Write Supabase diblok oleh Engine V3 staging. Production tidak berubah.');return Promise.resolve(new Response(JSON.stringify({ok:false,error:'ENGINE_V3_STAGING_READ_ONLY'}),{status:403,headers:{'content-type':'application/json'}}))}return nativeFetch(input,init)};
function notify(type,title,msg){if(typeof window.editorToast==='function')return window.editorToast(msg,type==='warning'?'info':type,title);const old=document.getElementById('diniV3StageNotice');old?.remove();const n=document.createElement('div');n.id='diniV3StageNotice';n.style.cssText='position:fixed;left:50%;top:18px;transform:translateX(-50%);z-index:2147483647;max-width:min(92vw,520px);background:#111;color:#fff;border:1px solid '+(type==='error'?'#8b3d3d':type==='success'?'#355f49':'#665b1f')+';border-radius:14px;padding:12px 14px;box-shadow:0 22px 70px #0008;font:12px/1.45 system-ui';n.innerHTML='<strong style="display:block;margin-bottom:3px">'+esc(title)+'</strong><span style="color:#aaa">'+esc(msg)+'</span>';document.body.appendChild(n);setTimeout(()=>n.remove(),type==='error'?5500:2800)}
function mountBadge(){if(document.getElementById('diniV3StageBadge'))return;const b=document.createElement('div');b.id='diniV3StageBadge';b.style.cssText='position:fixed;right:14px;bottom:14px;z-index:2147483000;background:#101713;color:#f5fff7;border:1px solid #38664c;border-radius:14px;padding:9px 11px;box-shadow:0 16px 50px #0007;font:11px/1.35 system-ui;pointer-events:none';b.innerHTML='<strong style="display:block;color:#7ae69a">ENGINE V3 STAGING</strong><span style="color:#a4b0a7">Production UI · READ ONLY · '+VERSION+'</span>';document.body.appendChild(b)}
function disableWrites(){for(const id of ['saveDraftBtn','b2UploadBtn']){const b=document.getElementById(id);if(!b)continue;b.disabled=true;b.dataset.v3StagingBlocked='1';b.title='Disabled in Engine V3 read-only staging';if(/simpan|save|upload/i.test(b.textContent||''))b.textContent=(id==='saveDraftBtn'?'🔒 Simpan disabled · STAGING':'🔒 Upload disabled · STAGING')}}
function markToolbar(text){const t=document.querySelector('.preview-toolbar');if(t&&!t.querySelector('[data-v3-stage]')){const s=document.createElement('span');s.dataset.v3Stage='1';s.style.cssText='margin-left:8px;color:#7ae69a;font-weight:800;font-size:10px;letter-spacing:.07em';s.textContent=text;t.appendChild(s)}}
function cloneClean(doc){const root=doc?.documentElement?.cloneNode(true);if(!root)return'';root.querySelectorAll('.native-selected-outline').forEach(n=>n.classList.remove('native-selected-outline'));root.querySelectorAll('#fetch-v2-editor-style,#template-v2-editor-style,[data-dini-v3-inspector-overlay]').forEach(n=>n.remove());return '<!doctype html>\n'+root.outerHTML}
function attrEsc(v){return String(v??'').replace(/\\/g,'\\\\').replace(/"/g,'\\"')}
function unique(doc,s){try{return doc.querySelectorAll(s).length===1}catch{return false}}
function rootSelector(el,base,cand){const nid=el.getAttribute('data-native-node-id');if(nid){const s='[data-native-node-id="'+attrEsc(nid)+'"]';if(unique(base,s)&&unique(cand,s))return s}for(const a of ['data-native-edit-id','data-native-media-proxy']){const v=String(el.getAttribute(a)||'').trim();if(v&&!/[\s,]/.test(v)){const s='['+a+'="'+attrEsc(v)+'"]';if(unique(base,s)&&unique(cand,s))return s}}return''}
function deriveDelta(baselineHtml,candidateHtml){const p=new DOMParser(),base=p.parseFromString(baselineHtml,'text/html'),cand=p.parseFromString(candidateHtml,'text/html'),ops=[],dedupe=new Set();const add=(type,selector,key,value)=>{const sig=type+'|'+selector+'|'+(key||'');if(dedupe.has(sig)||ops.length>=64)return;dedupe.add(sig);ops.push({id:'stage-'+(ops.length+1),type,selector,key:key||'',value:String(value??'')})};const attrs=['style','src','data-src','srcset','data-srcset','href','data-settings','data-native-slideshow-urls','data-thumbnail'];
for(const ce of cand.querySelectorAll('[data-native-node-id],[data-native-edit-id],[data-native-media-proxy]')){const s=rootSelector(ce,base,cand);if(!s)continue;const be=base.querySelector(s);if(!be)continue;for(const a of attrs){const bv=be.getAttribute(a),cv=ce.getAttribute(a);if(bv!==cv)add('attribute',s,a,cv??'')}if(be.childElementCount===0&&ce.childElementCount===0&&be.textContent!==ce.textContent)add('text',s,'',ce.textContent||'');for(const tag of ['img','a','video','audio','source','iframe']){const bs=be.querySelectorAll(tag),cs=ce.querySelectorAll(tag);if(bs.length!==1||cs.length!==1)continue;const ss=s+' '+tag;for(const a of attrs){const bv=bs[0].getAttribute(a),cv=cs[0].getAttribute(a);if(bv!==cv)add('attribute',ss,a,cv??'')}if(bs[0].childElementCount===0&&cs[0].childElementCount===0&&tag==='a'&&bs[0].textContent!==cs[0].textContent)add('text',ss,'',cs[0].textContent||'')}}}
return{version:1,operations:ops}}
function setupEditor(){const frame=document.getElementById('previewFrame');if(!frame)return;const isFetch=location.pathname.includes('/dashboard-admin-fetch-editor'),isTemplate=location.pathname.includes('/dashboard-admin-edit');if(!isFetch&&!isTemplate)return;let baselineHtml='',last=null,busy=false;const mode=isFetch?'fetch-create':'template-update';markToolbar('ENGINE V3 AUTHORITY · '+(isFetch?'FETCH':'TEMPLATE EDIT'));
function captureBaseline(){if(baselineHtml)return true;const raw=String(frame.srcdoc||'').trim();if(raw.length>200){baselineHtml=raw;document.documentElement.dataset.v3BaselineCaptured='1';return true}try{const h=cloneClean(frame.contentDocument);if(h.length>200){baselineHtml=h;document.documentElement.dataset.v3BaselineCaptured='1';return true}}catch{}return false}
frame.addEventListener('load',()=>setTimeout(captureBaseline,30));setTimeout(captureBaseline,400);
async function finalize(show=true){if(busy)return last;if(!captureBaseline()){notify('warning','Engine V3','Baseline preview belum siap. Tunggu preview selesai dimuat.');return null}let candidate='';try{candidate=cloneClean(frame.contentDocument)}catch{}if(!candidate){notify('error','Engine V3 gagal','Candidate preview tidak dapat dibaca.');return null}const delta=deriveDelta(baselineHtml,candidate);busy=true;notify('info','Engine V3','Menerapkan '+delta.operations.length+' delta melalui immutable renderer…');try{const r=await nativeFetch('/api/staging/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,source:location.href,template_id:String(window.__DINI_TEMPLATE_EDITOR_SCOPE__?.template_id||''),baselineHtml,delta})}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||('HTTP '+r.status));last=d;window.DINI_V3_STAGING_LAST=d;document.documentElement.dataset.engineV3Authority='1';if(show){frame.removeAttribute('src');frame.srcdoc=d.html}const gate=d.report?.status||'UNKNOWN';markToolbar('ENGINE V3 '+gate);notify(gate==='PASS'?'success':'warning','Engine V3 '+gate,delta.operations.length+' delta · output '+String(d.integrity?.outputHash||'').slice(0,10));return d}catch(e){notify('error','Engine V3 APPLY gagal',e.message||String(e));throw e}finally{busy=false}}
const apply=document.getElementById('applyBtn');if(apply)apply.addEventListener('click',()=>setTimeout(()=>finalize(true).catch(()=>{}),180));const clean=document.getElementById('cleanPreviewBtn');if(clean)document.addEventListener('click',e=>{if(e.target!==clean&&!e.target.closest?.('#cleanPreviewBtn'))return;e.preventDefault();e.stopImmediatePropagation();finalize(false).then(d=>{if(!d)return;const w=window.open('','_blank','noopener');if(!w){notify('warning','Preview diblokir','Izinkan popup untuk Preview Bersih.');return}w.document.open();w.document.write(d.html);w.document.close()}).catch(()=>{})},true);window.DINI_V3_STAGING={version:VERSION,mode,finalize,get baselineReady(){return!!baselineHtml},get last(){return last}}}
function init(){mountBadge();disableWrites();setupEditor();setTimeout(disableWrites,900);nativeFetch('/health',{cache:'no-store'}).then(r=>r.json()).then(h=>{document.documentElement.dataset.engineV3Health=h?.engine||'unknown'}).catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();`;
