import {createFreezeEnvelope} from './freeze.js';
import {runRegressionGate} from './regression.js';
import {fetchRaw,parseTarget} from './analyzer.js';
import {STAGING_CLIENT} from './staging-client.js';

const PROD='https://www.dini-faqih.my.id';
const MAX_HTML=6_000_000;
const json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}});
const redirect=to=>new Response(null,{status:302,headers:{location:to,'cache-control':'no-store'}});

function injectClient(html){const tag='<script src="/__v3/staging-client.js"></script>';if(String(html).includes('/__v3/staging-client.js'))return html;if(/<head[^>]*>/i.test(html))return String(html).replace(/<head([^>]*)>/i,'<head$1>'+tag);return tag+html}
function stagingHome(engine){return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Engine V3 Production UI Staging</title><style>:root{font-family:Inter,system-ui;color-scheme:dark;background:#080808;color:#f7f7f7}body{margin:0}.x{max-width:920px;margin:auto;padding:42px 22px}.card{border:1px solid #2a2a2a;background:#101010;border-radius:22px;padding:22px;margin:14px 0}.pill{display:inline-block;border:1px solid #355f49;background:#10251a;border-radius:999px;padding:7px 10px;color:#7ae69a;font-size:12px}h1{font-size:clamp(34px,6vw,62px);line-height:1;margin:16px 0}.muted{color:#999;line-height:1.65}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions a{color:#fff;text-decoration:none;border:1px solid #333;background:#171717;padding:12px 15px;border-radius:13px;font-weight:700}.actions a.primary{border-color:#355f49;background:#10251a}</style></head><body><main class="x"><span class="pill">${engine} · READ ONLY STAGING</span><h1>Production UI + Engine V3</h1><p class="muted">Tampilan berasal dari production asli. Source Fetch menggunakan V3 fetch. Fetch Editor dan Template Editor memakai production UI sebagai kontrol, lalu APPLY difinalkan oleh immutable V3 delta renderer. Write Supabase/Storage diblok di origin staging.</p><section class="card"><h2>Fetch workflow</h2><div class="actions"><a class="primary" href="/dashboard-admin-fetch/?engine_v3=1&staging_v3=1">Buka Fetch</a><a href="/dashboard-admin-fetch-editor/?engine_v3=1&staging_v3=1">Fetch Editor</a></div></section><section class="card"><h2>Template workflow</h2><div class="actions"><a class="primary" href="/dashboard-admin-template/?engine_v3=1&staging_v3=1">Template Library</a></div><p class="muted">Masuk Edit dari Template Library agar UUID template/record tetap memakai flow production.</p></section><section class="card"><h2>Diagnostics</h2><div class="actions"><a href="/">Engine Lab / Cockpit</a><a href="/health">Health JSON</a></div></section></main></body></html>`}

export function stagingClient(engine){const js=`window.__DINI_V3_STAGING_ENGINE__=${JSON.stringify(engine)};\n`+STAGING_CLIENT;return new Response(js,{headers:{'content-type':'text/javascript; charset=UTF-8','cache-control':'no-store'}})}
export async function stagingFetchSource(url){const target=parseTarget(url.searchParams.get('url')),raw=await fetchRaw(target);return json({ok:true,url:raw.finalUrl,html:raw.html,bytes:new TextEncoder().encode(raw.html).length,contentType:raw.contentType,engine:'v3-fetch-raw'})}
export async function stagingRender(request){let body;try{body=await request.json()}catch{throw new Error('Body staging render harus JSON.')};const baselineHtml=String(body?.baselineHtml||'');if(!baselineHtml||baselineHtml.length>MAX_HTML)throw new Error('Baseline HTML staging kosong atau terlalu besar.');const source=String(body?.source||'https://staging.invalid/');const envelope=await createFreezeEnvelope({source,rawHtml:baselineHtml,runtimeHtml:baselineHtml,browserMs:0,transport:{status:200,contentType:'text/html',finalUrl:source}});const delta=body?.delta||{version:1,operations:[]};const report=await runRegressionGate(envelope,delta);return json({ok:true,mode:body?.mode||'unknown',template_id:body?.template_id||null,html:report.html,integrity:report.integrity,matches:report.matches,report:{status:report.status,pass:report.pass,checks:report.checks,failures:report.failures,warnings:report.warnings}})}

export async function proxyProduction(request,engine){const src=new URL(request.url),target=new URL(src.pathname+src.search,PROD);const init={method:request.method,headers:new Headers(request.headers),redirect:'manual'};init.headers.set('host',new URL(PROD).host);if(!['GET','HEAD'].includes(request.method)){if(src.pathname==='/api/fetch-source')return stagingFetchSource(src);if(src.pathname==='/api/fetch-asset')return fetch(target,request);return json({ok:false,error:'ENGINE_V3_STAGING_READ_ONLY'},403)}const res=await fetch(target,init);const headers=new Headers(res.headers);headers.delete('content-length');headers.delete('content-encoding');headers.delete('content-security-policy');headers.delete('content-security-policy-report-only');headers.set('cache-control','no-store');headers.set('x-dini-v3-staging','1');const ct=(headers.get('content-type')||'').toLowerCase();if(ct.includes('text/html')){const html=injectClient(await res.text());return new Response(html,{status:res.status,headers})}return new Response(res.body,{status:res.status,headers})}

export async function stagingRoute(request,engine){const url=new URL(request.url);if(url.pathname==='/staging'||url.pathname==='/staging/')return new Response(stagingHome(engine),{headers:{'content-type':'text/html; charset=UTF-8','cache-control':'no-store'}});if(url.pathname==='/staging/fetch')return redirect('/dashboard-admin-fetch/?engine_v3=1&staging_v3=1');if(url.pathname==='/staging/fetch-editor')return redirect('/dashboard-admin-fetch-editor/?engine_v3=1&staging_v3=1');if(url.pathname==='/staging/templates')return redirect('/dashboard-admin-template/?engine_v3=1&staging_v3=1');if(url.pathname==='/__v3/staging-client.js')return stagingClient(engine);return null}
