import {createFreezeEnvelope} from './freeze.js';
import {fetchRaw,parseTarget} from './analyzer.js';
import {FULL_STAGING_CLIENT} from './staging-full-client.js';
import {EDITOR_FIX_CLIENT,EDITOR_INNER_SANDBOX} from './staging-editor-fixes.js';

const PROD='https://www.dini-faqih.my.id';
const MAX_HTML=6_000_000;
const json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}});
const redirect=to=>new Response(null,{status:302,headers:{location:to,'cache-control':'no-store'}});

function isEngineShell(path){return path==='/dashboard-admin-fetch'||path==='/dashboard-admin-fetch/'||path.includes('/dashboard-admin-fetch/preview')||path.includes('/dashboard-admin-fetch-editor')||path.includes('/dashboard-admin-edit')}
function stripV2Authority(html,path){if(!isEngineShell(path))return String(html);return String(html).replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi,(all,attrs)=>{const src=(String(attrs).match(/\bsrc\s*=\s*["']([^"']+)["']/i)||[])[1]||'';if(/@supabase\/supabase-js/i.test(src)||/admin-auth-guard\.js/i.test(src)||/zip-builder\.js/i.test(src))return all;return''})}
function injectClient(html,path){const fix=isEngineShell(path)?'<script src="/__v3/staging-editor-fixes.js"></script>':'';const full='<script src="/__v3/full-staging-client.js"></script>';const tag=fix+full;if(String(html).includes('/__v3/full-staging-client.js'))return html;if(/<head[^>]*>/i.test(html))return String(html).replace(/<head([^>]*)>/i,'<head$1>'+tag);return tag+html}
function stagingHome(engine){return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Engine V3 Production UI Staging</title><style>:root{font-family:Inter,system-ui;color-scheme:dark;background:#080808;color:#f7f7f7}body{margin:0}.x{max-width:920px;margin:auto;padding:42px 22px}.card{border:1px solid #2a2a2a;background:#101010;border-radius:22px;padding:22px;margin:14px 0}.pill{display:inline-block;border:1px solid #355f49;background:#10251a;border-radius:999px;padding:7px 10px;color:#7ae69a;font-size:12px}h1{font-size:clamp(34px,6vw,62px);line-height:1;margin:16px 0}.muted{color:#999;line-height:1.65}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions a{color:#fff;text-decoration:none;border:1px solid #333;background:#171717;padding:12px 15px;border-radius:13px;font-weight:700}.actions a.primary{border-color:#355f49;background:#10251a}</style></head><body><main class="x"><span class="pill">${engine} · FULL V3 AUTHORITY · READ ONLY</span><h1>Production UI + Engine V3</h1><p class="muted">HTML/CSS memakai production UI. Script authority V2 disaring keluar pada Fetch, Preview, Fetch Editor, dan Template Editor. Browser Capture, Runtime Freeze, immutable envelope, semantic map, delta, renderer, regression gate, preview, dan package memakai Engine V3.</p><section class="card"><h2>Fetch workflow</h2><div class="actions"><a class="primary" href="/dashboard-admin-fetch/?staging_v3=full">Buka Fetch V3</a><a href="/dashboard-admin-fetch-editor/?staging_v3=full">Fetch Editor</a></div></section><section class="card"><h2>Template workflow</h2><div class="actions"><a class="primary" href="/dashboard-admin-template/?staging_v3=full">Template Library</a></div><p class="muted">Template legacy dimigrasikan sekali ke immutable V3 envelope di IndexedDB staging. Tidak ada write ke production.</p></section><section class="card"><h2>Diagnostics</h2><div class="actions"><a href="/">Engine Lab / Cockpit</a><a href="/health">Health JSON</a></div></section></main></body></html>`}

export function stagingFullClient(engine){return new Response(`window.__DINI_V3_STAGING_ENGINE__=${JSON.stringify(engine)};\n`+FULL_STAGING_CLIENT,{headers:{'content-type':'text/javascript; charset=UTF-8','cache-control':'no-store'}})}
export function stagingEditorFixClient(){return new Response(EDITOR_FIX_CLIENT,{headers:{'content-type':'text/javascript; charset=UTF-8','cache-control':'no-store'}})}
export function stagingEditorInnerSandbox(){return new Response(EDITOR_INNER_SANDBOX,{headers:{'content-type':'text/javascript; charset=UTF-8','cache-control':'no-store'}})}
export async function stagingFetchSource(url){const target=parseTarget(url.searchParams.get('url')),raw=await fetchRaw(target);return json({ok:true,url:raw.finalUrl,html:raw.html,bytes:new TextEncoder().encode(raw.html).length,contentType:raw.contentType,engine:'v3-fetch-raw'})}
export async function stagingFreezeHtml(request){let body;try{body=await request.json()}catch{throw new Error('Body freeze-html harus JSON.')};const html=String(body?.html||'');if(!html||html.length>MAX_HTML)throw new Error('Legacy saved HTML kosong atau terlalu besar.');const source=String(body?.source||'https://legacy-template.staging.invalid/');const envelope=await createFreezeEnvelope({source,rawHtml:html,runtimeHtml:html,browserMs:null,transport:{status:200,contentType:'text/html',finalUrl:source,migration:'legacy-saved-snapshot'}});return json({ok:true,migration:true,template_id:body?.template_id||null,envelope})}

function rewriteLocation(headers,requestUrl){const loc=headers.get('location');if(!loc)return;try{const dest=new URL(loc,PROD),origin=new URL(requestUrl).origin;if(dest.origin===new URL(PROD).origin)headers.set('location',origin+dest.pathname+dest.search+dest.hash)}catch{}}
export async function proxyProduction(request,engine){const src=new URL(request.url),target=new URL(src.pathname+src.search,PROD);const init={method:request.method,headers:new Headers(request.headers),redirect:'manual'};init.headers.set('host',new URL(PROD).host);if(!['GET','HEAD'].includes(request.method)){if(src.pathname==='/api/fetch-source')return stagingFetchSource(src);if(src.pathname==='/api/fetch-asset')return fetch(target,request);return json({ok:false,error:'ENGINE_V3_STAGING_READ_ONLY'},403)}const res=await fetch(target,init);const headers=new Headers(res.headers);headers.delete('content-length');headers.delete('content-encoding');headers.delete('content-security-policy');headers.delete('content-security-policy-report-only');headers.set('cache-control','no-store');headers.set('x-dini-v3-staging','full-authority');rewriteLocation(headers,request.url);const ct=(headers.get('content-type')||'').toLowerCase();if(ct.includes('text/html')){let html=await res.text();html=stripV2Authority(html,src.pathname);html=injectClient(html,src.pathname);return new Response(html,{status:res.status,headers})}return new Response(res.body,{status:res.status,headers})}

export async function stagingRoute(request,engine){const url=new URL(request.url);if(url.pathname==='/staging'||url.pathname==='/staging/')return new Response(stagingHome(engine),{headers:{'content-type':'text/html; charset=UTF-8','cache-control':'no-store'}});if(url.pathname==='/staging/fetch')return redirect('/dashboard-admin-fetch/?staging_v3=full');if(url.pathname==='/staging/fetch-editor')return redirect('/dashboard-admin-fetch-editor/?staging_v3=full');if(url.pathname==='/staging/templates')return redirect('/dashboard-admin-template/?staging_v3=full');if(url.pathname==='/__v3/full-staging-client.js')return stagingFullClient(engine);if(url.pathname==='/__v3/staging-editor-fixes.js')return stagingEditorFixClient();if(url.pathname==='/__v3/editor-inner-sandbox.js')return stagingEditorInnerSandbox();return null}
