import {DEFAULT_SOURCE,parseTarget,analyzeHtml,compareReports,fetchRaw,injectBase} from './v3/analyzer.js';
import {createFreezeEnvelope,envelopeSummary} from './v3/freeze.js';
import {applyEditDelta} from './v3/delta.js';
import {page} from './v3/ui.js';
import {augmentInspectorPage} from './v3/inspector.js';
import {augmentFinalPage} from './v3/final.js';
import {augmentFinalSyncPage} from './v3/final-sync.js';
import {augmentInspectorController} from './v3/inspector-controller.js';
import {runRegressionGate} from './v3/regression.js';
import {buildLifecycleManifest} from './v3/lifecycle.js';
import {stagingRoute,stagingFreezeHtml,stagingFetchSource,proxyProduction} from './v3/staging.js';

const ENGINE='3.11.1-staging.2';
const BASELINE='94c4fddccde5d714f6ca9a247b87a0a9ef833f75';
const json=(d,s=200,h={})=>new Response(JSON.stringify(d,null,2),{status:s,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store',...h}});
async function browserContent(env,target){if(!env.BROWSER?.quickAction)throw new Error('Browser Run binding belum aktif.');const r=await env.BROWSER.quickAction('content',{url:target.href});const ms=r.headers.get('X-Browser-Ms-Used')||r.headers.get('x-browser-ms-used');if(!r.ok)throw new Error(`Browser Run content gagal HTTP ${r.status}: ${await r.text()}`);const body=await r.text();let html=body;try{const p=JSON.parse(body);html=p?.result?.content??p?.result??p?.content??body;if(typeof html!=='string')html=JSON.stringify(html)}catch{}return{html,browserMs:ms?Number(ms):null}}
async function analyze(url){const t=parseTarget(url.searchParams.get('url')),raw=await fetchRaw(t);return json({ok:true,engine:ENGINE,capturedAt:new Date().toISOString(),transport:{status:raw.status,contentType:raw.contentType,finalUrl:raw.finalUrl},report:await analyzeHtml(raw.html,raw.finalUrl,'raw-source')})}
async function capture(url,env){const t=parseTarget(url.searchParams.get('url')),raw=await fetchRaw(t),a=await analyzeHtml(raw.html,raw.finalUrl,'raw-source'),b=await browserContent(env,t),c=await analyzeHtml(b.html,raw.finalUrl,'browser-rendered');return json({ok:true,engine:ENGINE,capturedAt:new Date().toISOString(),browserMsUsed:b.browserMs,raw:a,rendered:c,comparison:compareReports(a,c)})}
async function freezeRuntime(url,env){const t=parseTarget(url.searchParams.get('url')),raw=await fetchRaw(t),runtime=await browserContent(env,t);const envelope=await createFreezeEnvelope({source:raw.finalUrl,rawHtml:raw.html,runtimeHtml:runtime.html,browserMs:runtime.browserMs,transport:{status:raw.status,contentType:raw.contentType,finalUrl:raw.finalUrl}});return json({ok:true,engine:ENGINE,envelope,summary:envelopeSummary(envelope)})}
async function deltaApply(request){let body;try{body=await request.json()}catch{throw new Error('Body delta harus JSON.')};const result=await applyEditDelta(body?.envelope,body?.delta||{});return json({ok:true,engine:ENGINE,phase:'FULL-V3-STAGING',...result})}
async function regression(request){let body;try{body=await request.json()}catch{throw new Error('Body regression harus JSON.')};const report=await runRegressionGate(body?.envelope,body?.delta||{});return json({ok:true,engine:ENGINE,report})}
async function lifecycle(request){let body;try{body=await request.json()}catch{throw new Error('Body lifecycle harus JSON.')};const manifest=await buildLifecycleManifest(body||{});return json({ok:true,engine:ENGINE,manifest})}
async function screenshot(url,env){const t=parseTarget(url.searchParams.get('url'));if(!env.BROWSER?.quickAction)throw new Error('Browser Run binding belum aktif.');return env.BROWSER.quickAction('screenshot',{url:t.href,screenshotOptions:{fullPage:true,type:'png'}})}
async function render(url){const t=parseTarget(url.searchParams.get('url')),raw=await fetchRaw(t);return new Response(injectBase(raw.html,raw.finalUrl),{headers:{'content-type':'text/html; charset=UTF-8','cache-control':'no-store','x-dini-v3-mode':'raw-baseline-render-envelope','x-dini-v3-source':raw.finalUrl}})}
export default{async fetch(request,env){const url=new URL(request.url);try{const stage=await stagingRoute(request,ENGINE);if(stage)return stage;if(url.pathname==='/health')return json({ok:true,service:'dinifaqih-engine-v3-lab',engine:ENGINE,phase:'FULL-V3-PRODUCTION-UI-STAGING',branch:'engine/v3-source-native-fidelity',baseline:BASELINE,browserBinding:Boolean(env.BROWSER),popupSystem:true,runtimeDeltaBridge:true,navigationGuard:true,observerLoopGuard:true,selectorInspector:true,clickToEdit:true,editorClickPickerFix:true,editorLiveDeltaGuard:true,editorProtectionNeutralizer:true,visualControls:true,semanticMap:true,singleRendererAuthority:true,indexedDbSession:true,packageZip:true,regressionGate:true,lifecycleContract:true,productionUiStaging:true,stagingReadOnly:true,fetchBrowserCaptureV3:true,fetchRuntimeFreezeV3:true,fetchSemanticMapV3:true,fetchEditorFullV3:true,templateEditorFullV3:true,legacyTemplateMigrationToV3:true,v2AuthorityScriptsFiltered:true,productionDatabaseWrites:false});if(url.pathname==='/api/analyze')return analyze(url);if(url.pathname==='/api/capture')return capture(url,env);if(url.pathname==='/api/freeze')return freezeRuntime(url,env);if(url.pathname==='/api/delta/apply'&&request.method==='POST')return deltaApply(request);if(url.pathname==='/api/regression'&&request.method==='POST')return regression(request);if(url.pathname==='/api/lifecycle/manifest'&&request.method==='POST')return lifecycle(request);if(url.pathname==='/api/staging/freeze-html'&&request.method==='POST')return stagingFreezeHtml(request);if(url.pathname==='/api/fetch-source')return stagingFetchSource(url);if(url.pathname==='/api/screenshot')return screenshot(url,env);if(url.pathname==='/render')return render(url);if(url.pathname==='/'){let html=page(request.url,{engine:ENGINE,baseline:BASELINE,defaultSource:DEFAULT_SOURCE});html=augmentInspectorPage(html);html=augmentFinalPage(html);html=augmentFinalSyncPage(html);html=augmentInspectorController(html);return new Response(html,{headers:{'content-type':'text/html; charset=UTF-8','cache-control':'no-store'}})}return proxyProduction(request,ENGINE)}catch(e){return json({ok:false,engine:ENGINE,error:e?.message||String(e)},500)}}};
