const dns = require('node:dns').promises;
const net = require('node:net');
const CHUNK = 3_000_000;
const TIMEOUT = 25_000;
function isPrivate4(ip){const p=ip.split('.').map(Number);return p.length!==4||p[0]===0||p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||p[0]>=224}
function blocked(ip){const f=net.isIP(ip);if(f===4)return isPrivate4(ip);if(f===6){const v=ip.toLowerCase().split('%')[0];return v==='::'||v==='::1'||v.startsWith('fc')||v.startsWith('fd')||/^fe[89ab]/.test(v)||v.startsWith('ff')}return true}
async function validate(u){if(!['http:','https:'].includes(u.protocol))throw Error('URL asset harus http/https.');const h=u.hostname.toLowerCase();if(!h||h==='localhost'||h.endsWith('.local'))throw Error('Host lokal diblok.');if(net.isIP(h)){if(blocked(h))throw Error('IP private diblok.');return}const a=await dns.lookup(h,{all:true,verbatim:true});if(!a.length||a.some(x=>blocked(x.address)))throw Error('Host asset mengarah ke jaringan private.')}
function safeName(u,ct){let n='asset';try{n=decodeURIComponent(new URL(u).pathname.split('/').pop()||'asset')}catch{};n=n.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-120)||'asset';if(!/\.[a-z0-9]{2,5}$/i.test(n)){const m={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','video/mp4':'.mp4','audio/mpeg':'.mp3'}[String(ct||'').split(';')[0]];if(m)n+=m}return n}
module.exports=async function(req,res){try{const raw=String(req.query?.url||'');if(!raw)throw Error('URL asset wajib diisi.');let u=new URL(raw);await validate(u);const offset=Math.max(0,Number(req.query?.offset||0)||0);const size=Math.min(CHUNK,Math.max(64*1024,Number(req.query?.size||CHUNK)||CHUNK));const c=new AbortController(),tm=setTimeout(()=>c.abort(),TIMEOUT);let r;try{r=await fetch(u.href,{redirect:'follow',signal:c.signal,headers:{Range:`bytes=${offset}-${offset+size-1}`,'User-Agent':'Mozilla/5.0 (compatible; DiniAnif-AssetGenerator/1.3.3)'}})}finally{clearTimeout(tm)}if(!r.ok&&r.status!==206)throw Error(`Asset HTTP ${r.status}`);const ct=r.headers.get('content-type')||'application/octet-stream';const cr=r.headers.get('content-range')||'';const cl=Number(r.headers.get('content-length')||0);let total=0;const m=cr.match(/\/(\d+)$/);if(m)total=Number(m[1]);else if(r.status===200)total=cl;const ab=await r.arrayBuffer();if(ab.byteLength>3_500_000)throw Error('Chunk asset melebihi batas aman Vercel.');if(offset>0&&r.status!==206)throw Error('Server sumber tidak mendukung Range untuk asset besar.');res.statusCode=200;res.setHeader('Content-Type',ct);res.setHeader('Cache-Control','no-store');res.setHeader('X-Asset-Total',String(total||ab.byteLength));res.setHeader('X-Asset-Offset',String(offset));res.setHeader('X-Asset-Name',encodeURIComponent(safeName(u.href,ct)));res.setHeader('X-Asset-Range',r.status===206?'1':'0');res.end(Buffer.from(ab));}catch(e){res.statusCode=e?.name==='AbortError'?504:422;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify({ok:false,error:e?.name==='AbortError'?'Fetch asset timeout.':(e.message||'Fetch asset gagal.')}))}}
